name: Vite React App CI/CD (Self-Hosted)

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Build Vite React App
        run: CI=false npm run build

      - name: 5. Deploy to Server (LOCAL)
        run: |
          TARGET_DIR="/var/www/html/application/frontend"
          BUILD_DIR="$GITHUB_WORKSPACE/build"

          echo "Removing old build..."
          rm -rf ${TARGET_DIR}/build

          echo "Copying new build..."
          cp -r $BUILD_DIR ${TARGET_DIR}/

      - name: 6. Reload Nginx
        run: |
          echo "Reloading Nginx........"
          sudo systemctl reload nginx
          echo "Deployment complete!"